config/routes.rb
Rails.application.routes.draw do
  resources :owners, except: [:new, :create] do
    resources(:items)
  end

  resources(:items) do
    resources :supplies
  end

  resources :supplies
  get '/items', to: "items#index"
  get '/items/:id', to: "items#show"
  get '/signup', to: "owners#new", as: "signup"
  post '/signup', to: "owners#create"
  get '/login', to: "sessions#new", as: "login"
  post '/login', to: "sessions#create"
  post '/logout', to: "sessions#destroy"
  get "/auth/facebook/callback", to: "sessions#create_with_fb"
  root 'owners#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :supplies
  has_many :owners, through: :supplies

  accepts_nested_attributes_for :supplies

  validates_presence_of :name
  validates_uniqueness_of :name

  




end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :supplies
  has_many :items, through: :supplies
  has_secure_password

  validates_uniqueness_of :username 
  validates_presence_of :username
  validates :username, format: {with: /\A^[a-z0-9]*$\z/, message: "-->  Uppercase, Special Characters & Spaces are NOT allowed. Please try again"}
  


end

app/models/supply.rb
class Supply < ApplicationRecord
  belongs_to :item
  belongs_to :owner
  validates_presence_of :quantity, :unit

  scope(:quantity_search, ->(quantity) { self.where("quantity >= ?", quantity) })

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method(:current_owner)

  def current_owner
    @current_owner = Owner.find_by(id: session[:owner_id])
  end

  def req_login
    redirect_to '/login' if !current_owner
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action(:set_item, except: [:index, :new, :create])
  before_action(:req_login)

  layout "application"

  def index
    if params[:owner_id]
      owner = Owner.find_by(id: params[:owner_id])
      @items = owner.items
     else
      @items = Item.all
    end
  end

  def show
  end
  
  def new
    @item = Item.new
    @item.supplies.build(owner: current_owner)
    @supplies = @item.supplies.select{|p| p.owner_id == current_owner.id}
  end

  def create
    @item = Item.new(item_params)
    @item.supplies.each do |p|
      p.owner = current_owner
    end
    if @item.save
        redirect_to item_path(@item)
    else
      @errors = @item.errors.full_messages
      render :new
    end
  end

  def edit
    @supplies = @item.supplies.where(owner_id: current_owner.id)
  end

  def update
    if @item.update(item_params)
      redirect_to(item_path(@item))
    else
      @supplies = @item.supplies.select do |p|
        p.owner_id == current_owner.id
      end
      @errors = @item.errors.full_messages
      render :edit
    end
  end


  def destroy
    @item.delete
    redirect_to items_path
  end

####
  private

    def item_params
      params.require(:item).permit(:name, supplies_attributes: [:unit, :quantity, :owner_id])
    end

    def set_item
      @item = Item.find_by(id: params[:id], name: params[:name])
    end


end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action(:req_login, except: [:new, :create])

  def new
    @owner = Owner.new
  end

  def home
  end

  def create
    @owner = Owner.new(owner_params)
    if @owner.save
      session[:owner_id] = @owner.id
      redirect_to owner_items_path(@owner)
    else
      @errors = @owner.errors.full_messages
      render :new
    end
  end




  private

  def owner_params
    params.require(:owner).permit(:username, :fname, :lname, :company_name, :password, :location, :password_confirmation)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @owner = Owner.new
  end

  def create
     @owner = Owner.find_by(username: params[:owner][:username])
      if  @owner &&  @owner.authenticate(params[:owner][:password])
      session[:owner_id] =  @owner.id
      redirect_to owner_items_path(@owner)
    elsif  @owner
      @errors = ["Invalid Password"]
      render :new
    else
      @errors = ["Invalid Username and/or Password"]
      render :new
    end
  end
    
  def create_with_fb
    owner = Owner.find_or_create_by(username: fb_auth['info']['name']) do |p|
      p.password = 'password'
    end
    if @owner.save
      session[:owner_id] = @owner.id
      redirect_to owner_items_path(owner)
    else
       redirect_to signup_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

####
  private

  def fb_auth
    self.request.env['omniauth.auth']
  end


end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  before_action(:req_login)
  layout "application"

  def index
    if params[:quantity]
      @supplies = Supply.quantity_search(params[:quantity])
    else
      @supplies = Supply.all
    end
  end

  def edit
  end

  def new
    if params[:item_id]
      @item = Item.find_by(id: params[:item_id])
      @supply = @item.supplies.build
      @items = Item.all
    else
      @supply = Supply.new
      @items = Item.all
    end

  end

  def create
    @supply = Supply.create(supply_params)
    @supply.owner = current_owner
    if params[:item_id]
      @supply.item_id = params[:item_id]
    end
    if @supply.save
      redirect_to items_path
    else
      @items = Items.all
      render :new
    end
  end



  private

  def supply_params
    params.require(:supply).permit(:quantity, :unit, :item_id, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper

  

end

app/helpers/owners_helper.rb
module OwnersHelper
  

end

app/helpers/supplies_helper.rb
module SuppliesHelper

  def show_item_name(p, index)
    p.item.name if index
  end

  def form_url_helper(item)
    item ? item_supplies_path(item) : login_path
  end


end

app/views/items/_form.html.erb
<%=form_for(@item) do |f|%>
  <%=f.label("Select Item:") %><br/>
   <%=f.collection_select :id, Item.all, :id, :name %> <br/><br/>
  <h4><%=f.label("How Much Do You Want to Add?") %><br/></h4>
    <%=f.fields_for :supplies do |m| %> 
      <%=m.label "Quantity:"%><br/>
      <%=m.number_field :quantity%><br/><br/>
      <%=m.label "Unit:"%><br/>
      <%=m.text_field  :unit %><br/><br>
      <%=m.hidden_field :owner_id, value: current_owner.id %>
    <%end%>
  <%=f.submit "Save Into My Supplies"%>
<%end%>

app/views/items/edit .html.erb
<% @errors && @errors.each do |e| %>
  <li><%=e%></li>
<%end%>
<%=render('form')%>

app/views/items/index.html.erb
<h1>Good Day!</h1>

<h5>Below is Your  Tactical Supply List. </h5>
<%= link_to "Add Items", new_item_path %>

<% @items.each do |i| %>
  <li><%=link_to(i.name, item_path(i))%>
  </li>
 <%end%>

  
  
  

app/views/items/new.html.erb
<% @errors && @errors.each do |e| %>
  <li><%=e%></li>
<%end%>
<%=render('form')%>

app/views/items/show.html.erb
<h1><%=@item.name%></h1>
 
<%=render partial: 'supplies/supplies', locals: {supplies: @item.supplies, index: false}%><br>


<%=link_to "Edit / Change Your Supply", edit_item_path(@item) %><br><br>


<%=button_to("Delete", @item, method: :delete, data: { confirm: "Are You Positve You Want to Delete Item?" }) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tactical Supply</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <%if current_owner %>
    <%=link_to "All Suppliers Items", items_path %><br/>
    <%=link_to "Add a New Item", new_item_path %><br/>
     <%=link_to "Search by Inventory Numbers", supplies_path %><br/>
    <%=link_to "View My Items", owner_items_path(current_owner) %><br/><br/>
    <%= button_to "Log Out", logout_path, method: :post %><br/><br/> 
 
  <%end%>


   <%= yield %>
  </body>
</html>

app/views/owners/home.erb
<%if current_owner %>
<h1><%=current_owner.fname %>, Welcome to Gun Supply Tracker!</h1>
<h3><i>for your business needs</i></h3>
<%else %>
<h1>Welcome to Gun Supply Tracker!</h1>


<h3><i>for your business needs</i></h3>
<%= link_to "Login with an User Name", login_path %><br/>
<%= link_to 'Login / Continue with FaceBook', '' %><br/>
<%= link_to "Signup", signup_path %>
<%end%>

app/views/owners/new.html.erb
<h1>Sign Up</h1>
   
<% @errors && @errors.each do |e| %>
  <li><%=e%></li>
<%end%>

<%= form_for @owner, url: signup_path do |f| %>
  <%=f.label "First Name" %><br/><%=f.text_field :fname %><br/><br/>
  <%=f.label "Last Name" %><br/><%=f.text_field :lname %><br/><br/>
  <%=f.label "Username"%><br/><%=f.text_field :username %><br/><br/>
  <%=f.label "Company Name"%><br/><%=f.text_field :company_name %><br/><br/>
  <%=f.label "Location"%><br/><%=f.text_field :location %><br/><br/>
  <%=f.label "Password"%><br/><%=f.password_field :password %><br/><br/>
  <%=f.label "Password Confirmation"%><br/><%=f.password_field :password_confirmation %><br/><br/>
  <%=f.submit "Sign Up"%>
<%end%>

app/views/supplies/_supplies.html.erb
<%supplies.each do |m|%>
 <li><b><%=m.quantity%> <%=m.unit%></b><%=show_item_name(m, index)%><br/>
 <%end%>

app/views/supplies/index.html.erb
<h1>Search By Quantity from all Tactical Suppliers</h1>
<br/><br/>
<%= form_tag supplies_path, method: :get do %>
  <%=text_field_tag :quantity %>
  <%=submit_tag "Search"%>
<%end%><br/><br/>
 <%=render(partial: 'supplies', locals: {supplies: @supplies, index: true})%>

app/views/supplies/new.html.erb
<% @errors && @errors.each do |e| %>
  <li><%=e%></li>
<%end%>
  <%if @item%>
    <h3><%=@item.name%></h3>
  <%end%>
<%= form_for(@supply, url: form_url_helper(@item)) do |f|%>
  <%=f.label "Quantity"%><%=f.number_field(:quantity)%>
  <%=f.label "Units"%><%=f.text_field(:unit)%>
  <%if !@item%>
    <%=f.label "Item"%>
    <%= f.hidden_field :owner_id, value: current_owner.id %>
  <%end%>
  <%=f.submit("Save")%>
<%end%>